---

name: CI

on:
  pull_request:
    types:
      - opened
      - ready_for_review
      - reopened
      - synchronize
  push:
    branches:
      - master

jobs:
  lint_js:
    name: Lint (JS)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '26'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint:js

  lint_css:
    name: Lint (CSS)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '26'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint:css

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '26'

      - name: Install
        run: npm ci

      - name: Typecheck
        run: npm run typecheck

  build:
    name: Build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: '26'

      - name: Install
        run: npm ci

      - name: Build
        run: npm run build
